import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { format } from 'date-fns';

export interface ExportData {
  title: string;
  projectName: string;
  engineerName: string;
  inputs: Record<string, string | number>;
  results: Record<string, string | number>;
  formula?: string;
}

export const exportToPDF = (data: ExportData) => {
  const doc = new jsPDF();
  const dateStr = format(new Date(), 'yyyy-MM-dd HH:mm:ss');
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(0, 112, 243); // Primary blue
  doc.text("Engineering Gift", 14, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Smart ELV Calculations Report`, 14, 26);
  
  doc.line(14, 30, 196, 30);

  // Project Info
  doc.setFontSize(14);
  doc.setTextColor(20, 20, 20);
  doc.text(data.title, 14, 42);

  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(`Project: ${data.projectName || 'N/A'}`, 14, 50);
  doc.text(`Engineer: ${data.engineerName || 'N/A'}`, 14, 56);
  doc.text(`Date: ${dateStr}`, 14, 62);

  let currentY = 72;

  // Inputs Table
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text("Input Parameters", 14, currentY);
  
  const inputRows = Object.entries(data.inputs).map(([key, value]) => [key, value.toString()]);
  
  // @ts-ignore (jspdf-autotable types)
  doc.autoTable({
    startY: currentY + 4,
    head: [['Parameter', 'Value']],
    body: inputRows,
    theme: 'grid',
    headStyles: { fillColor: [240, 244, 248], textColor: [20, 20, 20] },
    styles: { fontSize: 10 },
  });

  // @ts-ignore
  currentY = doc.lastAutoTable.finalY + 12;

  // Formula
  if (data.formula) {
    doc.text("Formula Used", 14, currentY);
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    // @ts-ignore
    doc.autoTable({
      startY: currentY + 4,
      body: [[data.formula]],
      theme: 'plain',
      styles: { fillColor: [248, 250, 252], textColor: [40, 40, 40], fontStyle: 'italic', cellPadding: 4 },
    });
    // @ts-ignore
    currentY = doc.lastAutoTable.finalY + 12;
  }

  // Results Table
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text("Calculation Results", 14, currentY);

  const resultRows = Object.entries(data.results).map(([key, value]) => [key, value.toString()]);

  // @ts-ignore
  doc.autoTable({
    startY: currentY + 4,
    head: [['Output', 'Value']],
    body: resultRows,
    theme: 'grid',
    headStyles: { fillColor: [0, 112, 243], textColor: [255, 255, 255] },
    styles: { fontSize: 11, fontStyle: 'bold' },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Engineering Gift | Page ${i} of ${pageCount}`,
      105,
      290,
      { align: 'center' }
    );
  }

  const filename = `${data.title.toLowerCase().replace(/\s+/g, '_')}_${format(new Date(), 'yyyyMMdd')}.pdf`;
  doc.save(filename);
};

export const exportToExcel = (data: ExportData) => {
  const wb = XLSX.utils.book_new();

  // Create Info Sheet
  const infoData = [
    ["Engineering Gift - Smart ELV Calculations"],
    [""],
    ["Calculation Type", data.title],
    ["Project Name", data.projectName || "N/A"],
    ["Engineer Name", data.engineerName || "N/A"],
    ["Date Generated", format(new Date(), 'yyyy-MM-dd HH:mm:ss')],
  ];
  if (data.formula) {
    infoData.push(["Formula Used", data.formula]);
  }
  const wsInfo = XLSX.utils.aoa_to_sheet(infoData);
  XLSX.utils.book_append_sheet(wb, wsInfo, "Project Info");

  // Create Data Sheet
  const calcData = [
    ["INPUT PARAMETERS", ""],
    ["Parameter", "Value"],
    ...Object.entries(data.inputs),
    ["", ""],
    ["CALCULATION RESULTS", ""],
    ["Output", "Value"],
    ...Object.entries(data.results)
  ];
  
  const wsData = XLSX.utils.aoa_to_sheet(calcData);
  XLSX.utils.book_append_sheet(wb, wsData, "Calculations");

  const filename = `${data.title.toLowerCase().replace(/\s+/g, '_')}_${format(new Date(), 'yyyyMMdd')}.xlsx`;
  XLSX.writeFile(wb, filename);
};
